[project]
name = "meter-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.35.0",
    "flask==3.0.0",
    "gunicorn==21.2.0",
    "numpy>=1.24.0",
    "opencv-python-headless>=4.6.0",
    "pillow>=11.0.0",
    "python-dotenv==1.0.0",
    "ultralytics>=8.3.0",
    "werkzeug==3.0.1",
]
